### ISSUE TITLE
Service cannot be started due to System.FormatException

### ISSUE THREAD

**Issue by djqifs** [DouglasDwyer/IntegratedMinecraftServer#5]
IMS Service is presenting a string in US date format which prevents launch in any other country; US date formats are unusual from an international perspective (mm/dd/yyyy). 

This will raise a Windows Application Event under .Net Runtime of **1026 (Description: The process was terminated due to an unhandled exception.)** 

I haven't looked at the code, so it may be due to the library you're using or the way the input to that library presupposes a specific interpretation by that library.

Example details:

Exception Info: System.FormatException: String '10/25/2017 10:43:50 AM' was not recognized as a valid DateTime.
   at System.DateTimeParse.Parse(ReadOnlySpan`1 s, DateTimeFormatInfo dtfi, DateTimeStyles styles)
   at System.DateTime.Parse(String s)
   at RoyalXML.RoyalSerializer.StringToValueType(String data, Type type) in D:\Projects\RoyalXML\RoyalXML\RoyalSerializer.cs:line 354
   at RoyalXML.RoyalSerializer.LoadObject(XElement currentDocument, Type fieldType, Dictionary`2 typeDictionary) in D:\Projects\RoyalXML\RoyalXML\RoyalSerializer.cs:line 247
   at RoyalXML.RoyalSerializer.LoadObject(XElement currentDocument, Type fieldType, Dictionary`2 typeDictionary) in D:\Projects\RoyalXML\RoyalXML\RoyalSerializer.cs:line 304
   at RoyalXML.RoyalSerializer.LoadObject(XElement currentDocument, Type fieldType, Dictionary`2 typeDictionary) in D:\Projects\RoyalXML\RoyalXML\RoyalSerializer.cs:line 281
   at RoyalXML.RoyalSerializer.LoadObject(XElement currentDocument, Type fieldType, Dictionary`2 typeDictionary) in D:\Projects\RoyalXML\RoyalXML\RoyalSerializer.cs:line 275
   at RoyalXML.RoyalSerializer.LoadObject(XElement currentDocument, Type fieldType, Dictionary`2 typeDictionary) in D:\Projects\RoyalXML\RoyalXML\RoyalSerializer.cs:line 293
   at RoyalXML.RoyalSerializer.LoadObject(XElement currentDocument, Type fieldType, Dictionary`2 typeDictionary) in D:\Projects\RoyalXML\RoyalXML\RoyalSerializer.cs:line 304
   at RoyalXML.RoyalSerializer.XMLToObject(String xml) in D:\Projects\RoyalXML\RoyalXML\RoyalSerializer.cs:line 235
   at RoyalXML.RoyalSerializer.XMLToObject[T](String xml) in D:\Projects\RoyalXML\RoyalXML\RoyalSerializer.cs:line 370
   at IMS_Library.IMSConfigurationUtility.FromConfiguration[T](T imsConfiguration) in D:\Projects\IntegratedMinecraftServer\IMS-Library\IMSConfiguration.cs:line 59
   at IMS_Library.IMS.Execute() in D:\Projects\IntegratedMinecraftServer\IMS-Library\IMS.cs:line 152
   at IMS_Library.IMS.OnStart(String[] args) in D:\Projects\IntegratedMinecraftServer\IMS-Library\IMS.cs:line 211
   at System.ServiceProcess.ServiceBase.ServiceQueuedMainCallback(Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.ServiceProcess.ServiceBase.Run(ServiceBase[] services)
   at System.ServiceProcess.ServiceBase.Run(ServiceBase service)
   at IMS_Service.Program.Main(String[] args) in D:\Projects\IntegratedMinecraftServer\IMS-Service\Program.cs:line 39

**Comment by DouglasDwyer** [comment]
Interesting that `DateTime.Parse()` will only accept times formatted in the current time system. I suppose this makes sense, because a date like 10/4/2020 would be valid in either system. I'll look into patching this; in theory, any configuration files (what IMS tries to read when it throws this error) generated by IMS should be in the correct time zone, but IMS comes with some pre-made configuration files that I've set up. I'll look into patching this - thanks for pointing it out.

**Comment by DouglasDwyer** [comment]
In the meantime, the workaround to this is to delete the pre-made version information file at the location: `C:\Program Files (x86)\IMS\Data\versioninformation.xml`. This file contains data on each version of Minecraft and its download links; IMS should regenerate this file (with the correct date formats) if you remove it. It may take IMS some time to gather data about Minecraft versions, though, which is why it comes pre-made.

**Comment by DouglasDwyer** [comment]
This issue was due to IMS reading configuration files that contained US dates when it expected dates formatted in other ways. This has been fixed with commit b456c13 and should roll out as a part of the v1.0.1.3 release. Thank you again for bringing this to my attention :)
